### ISSUE TITLE
KeyError when trying `Calibrate ensemble` in Terarium.

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#539]
Here is the error message: 

```python
ERROR    rq.worker:worker.py:1501 [Job 9036f8a8-7e55-4e77-aeec-e8d4ca120d67]: exception raised while executing (execute.run)
Traceback (most recent call last):
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/interfaces.py", line 303, in wrapped_model
    observe(solution, obs)
  File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/chirho/observational/internals.py", line 56, in _observe_dict
    obs = obs(rv)
          ^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/observation.py", line 45, in forward
    self.markov_kernel(k, state[k]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/observation.py", line 64, in markov_kernel
    return pyro.distributions.Normal(val, self.scale * torch.abs(val)).to_event(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/distributions/distribution.py", line 24, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/distributions/distribution.py", line 68, in __init__
    raise ValueError(
ValueError: Expected parameter scale (Tensor of shape (5,)) of distribution Normal(loc: torch.Size([5]), scale: torch.Size([5])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([0.0000, 0.0017, 0.0035, 0.0057, 0.0087], grad_fn=<MulBackward0>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/service/execute.py", line 37, in run
    output = eval(operation_name)(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/integration_utils/custom_decorators.py", line 29, in wrapped
    raise e
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/integration_utils/custom_decorators.py", line 10, in wrapped
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/interfaces.py", line 305, in ensemble_calibrate
    inferred_parameters = autoguide(wrapped_model)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/interfaces.py", line 273, in autoguide
    mvn_guide._setup_prototype()
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/infer/autoguide/guides.py", line 1002, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/infer/autoguide/guides.py", line 636, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/infer/autoguide/guides.py", line 157, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/interfaces.py", line 303, in wrapped_model
    observe(solution, obs)
  File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/chirho/observational/internals.py", line 56, in _observe_dict
    obs = obs(rv)
          ^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/nn/module.py", line 449, in __call__
    result = super().__call__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/observation.py", line 45, in forward
    self.markov_kernel(k, state[k]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/observation.py", line 64, in markov_kernel
    return pyro.distributions.Normal(val, self.scale * torch.abs(val)).to_event(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/pyro/distributions/distribution.py", line 24, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/five/Code/GitHub/pyciemss-service/.venv/lib/python3.11/site-packages/torch/distributions/distribution.py", line 68, in __init__
    raise ValueError(
ValueError: Expected parameter scale (Tensor of shape (5,)) of distribution Normal(loc: torch.Size([5]), scale: torch.Size([5])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([0.0000, 0.0017, 0.0035, 0.0057, 0.0087], grad_fn=<MulBackward0>)
                Trace Shapes:    
                 Param Sites:    
                Sample Sites:    
           model_weights dist | 2
                        value | 2
 model_0/persistent_beta dist |  
                        value |  
model_0/persistent_delta dist |  
                        value |  
model_0/persistent_alpha dist |  
                        value |  
 model_1/persistent_beta dist |  
                        value |  
model_1/persistent_gamma dist |  
                        value |  
```

**Comment by SamWitty** [comment]
Closing this issue, as `Calibrate ensemble` in Terarium is out-of-scope of PyCIEMSS. Please resubmit a minimal working example using PyCIEMSS that demonstrates the error.
